### ISSUE TITLE
Counter id

### ISSUE THREAD

**Issue by lambertchazal** [Markourai/DomoticzSuez#1]
Bonjour,

Comment puis-je retrouver le numéro de compteur à renseigner.
Après plusieurs tentatives et différents numéros essayé, le debug me sort toujours le message suivant : 

`>'Data':'b'["ERR","Aucune consommation n\'a \\u00e9t\\u00e9 enregistr\\u00e9e sur cette p\\u00e9riode"]''`

Cordialement,

**Comment by lambertchazal** [comment]
Problème résolu en suivant le lien :

`http://domotique.web2diz.net/recuperer-les-information-de-consommation-du-site-de-la-lyonnaise-des-eaux-sdei-1/`

**Comment by Markourai** [comment]
@lambertchazal 
parfait si vous avez trouvé et ça fait plaisir de voir qu'il est utilisé. le plugin est encore à améliorer car il n'arrive pas à mettre à jour les données lors d'un changement de mois
