### ISSUE TITLE
Data Time Format

### ISSUE THREAD

**Issue by Fabaude** [Markourai/DomoticzSuez#4]
Hello,
I installed the DomoticzSuez plugin from @yed30 and in my Domoticz LOGs, I see this error:
"SUEZ: Error in received JSON data time format: time data 'A' does not match format '%d/%m/%Y' during step idle for days of year 2022 and month 10". (other months too)
I was wondering if this error was mine or something else!
I don't know where to look...
If anyone has an idea, thank you in advance.
ps: I'm French and I use Google Translate so excuse me if there are language errors ;-)

**Comment by yed30** [comment]
Bonjour, votre Counter ID n'est pas bon ...
Pour le vérifier connectez vous au site [toutsur mon eau ](https://www.toutsurmoneau.fr) puis testez l'url suivante: 
https://www.toutsurmoneau.fr/mon-compte-en-ligne/statJData/2022/9/CounterID
cette url doit retourner un JSON avec des series de dates et valeurs

**Comment by Fabaude** [comment]
Rebonjour,
Alors, tout d'abord Merci de répondre.
Aprés connexion au compte "suez" et entrer l'url sur un nouvel onglet , la réponse est : 
[
"ERR",
"Aucune consommation n'a été enregistrée sur cette période"
]
Pourtant dans mon historique de données (sur "toutsurmoneau"), je peux voir mes consos par mois et jours.
Il y a même un fichier excel à télécharger !
Voilà ce que je peux vous dire.

**Comment by yed30** [comment]
vous avez bien remplacé CounterID par la valeur de votre identifiant de compteur (quelque chose comme 123456789) ?
Ce qui donnerait https://www.toutsurmoneau.fr/mon-compte-en-ligne/statJData/2022/9/123456789

Si vous passez votre souris sur le fichier excele, vous voyez apparaitre l'url où se trouve votre fichier. Cette url contient votre counterID

**Comment by Fabaude** [comment]
Bonjour et un grand MERCI
Pour moi, counter ID était mon numéro de compteur qui forcément ne me donnait rien !!!
En effet, en passant la souris sur le fichier excel dispo sur le site, l'url avec le bon numéro est apparue...(en bas à gauche).
Et maintenant toutes les consos remontent.
Je vous remercie encore de votre aide et de votre patience.
